config/routes.rb
Rails.application.routes.draw do

  get 'comments/index'

  get 'pay/new'

  get 'pay/show'

  get 'notificaciones/index'
  get 'notificaciones/marcarVitoRespuesta/:id' => 'notificaciones#marcarVitoRespuesta'

  get 'admin_panel/index'
  post 'admin_panel/recaudacion' => 'admin_panel#recaudacion'
  get 'admin_panel/recaudacion' => 'admin_panel#recaudacion'
  get 'admin_panel/rankingEslabones' => 'admin_panel#rankingEslabones'

  get 'users/passForm'
  post 'users/passReset'
  get 'users/passReset'

  get 'ranking/destroy/id'

  get 'ranking/new'

  get 'ranking/edit'

  get 'ranking/index'

  get 'ranking/id'

  post 'ranking/create'

  get 'ranking/update'

  get 'ranking/destroy'

  get 'ranking/show'

  root 'home#index'

  post 'comments/new' => 'comments#new'
  post 'comments/responder' => 'comments#responder'
  post 'comments/delete' => 'comments#delete'

  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :users
  resources :favors
  get 'favors/postulantes/:id' => 'favors#postulantes'
  get 'favors/aceptar_postulante/:favor/:id' => 'favors#aceptar_postulante'
  get 'favors/marcarComoRealizado/:favor' => 'favors#marcarComoRealizado'
  get 'favors/marcarComoNoRealizado/:favor' => 'favors#marcarComoNoRealizado'
  resources :offers
  post 'offers/new'
  get 'offers/marcarVistoPostulacion/:favor' => 'offers#marcarVistoPostulacion'
  get 'offers/marcarVistoRealizacion/:favor' => 'offers#marcarVistoRealizacion'
  
  resources :ranking
  resources :admin_panel
  resources :pay
  post 'pay/new'

end

app/controllers/admin_panel_controller.rb
class AdminPanelController < ApplicationController
	
  def index
  	if current_user.has_role? :admin
  	else 
    	flash[:danger] = "Usted no es administrador"
    	redirect_to ("/")
    end
  end

  def recaudacion
  	#dato = params["pay"]["inicio(1i)"].to_s
  	#flash[:danger] = "Inicio ."+inicio.to_s+". y la de fin: "+fin.to_s
    if current_user
      if current_user.has_role? :admin
  	     if (params["send"] == 'true')  
  		      @inicio = Date.new(  params["pay"]["inicio(1i)"].to_i,
                               	 params["pay"]["inicio(2i)"].to_i,
                                 params["pay"]["inicio(3i)"].to_i)

  		      @fin = Date.new(      params["pay"]["fin(1i)"].to_i,
                                	params["pay"]["fin(2i)"].to_i,
                                	params["pay"]["fin(3i)"].to_i)
  		      if @fin > @inicio
        	    @pays = Pay.where("created_at >= '"+@inicio.to_s+"' and created_at <= '"+@fin.to_s+"'")
            else 
        	    flash[:danger] = "Las fechas seleccionadas son incorrectas."
        	    redirect_to (:back)
            end
          end
      else
    	  flash[:danger] = "Usted no es administrador"
    	  redirect_to ("/")
      end
    else
      flash[:danger] = "Debe acceder al sistema para ver esta informacion."
      redirect_to ("/")
    end
  end

  def rankingEslabones
    if current_user
  	  if current_user.has_role? :admin
  		  @users = User.order('eslabon DESC')
  	  else 
    	 flash[:danger] = "Usted no es administrador"
    	 redirect_to ("/")
      end
    else
      flash[:danger] = "Debe acceder al sistema para ver esta informacion."
      redirect_to ("/")
    end
  end

end

app/helpers/admin_panel_helper.rb
module AdminPanelHelper
end

app/views/admin_panel/index.html.erb
<h1 style="margin-top:25px;">Panel de Administracion </h1>

<div class="row">
	<div class="col-sm-12">
		<h3 style="float: left;">Logros</h3>
		<%= link_to "Listado de Logros", ranking_index_path , :class => "btn btn-warning", :style => "float:left; margin-top:17px; margin-left: 15px;" %>
		<%= link_to "Agregar Logro", new_ranking_path(Ranking) , :class => "btn btn-warning", :style => "float:left; margin-top:17px; margin-left: 15px;" %>
	</div>

	<div class="col-sm-12" style="margin-top: 25px;">
		<h3 style="float: left;">Ganancias entre 2 fechas</h3>
		<a href="/admin_panel/recaudacion" class="btn btn-warning" style="float:left; margin-top:17px; margin-left: 15px;" > Ver </a>
	</div>

	<div class="col-sm-12" style="margin-top: 25px;">
		<h3 style="float: left;">Ranking de usuarios con mayor cantidad de eslabones</h3>
		<a href="/admin_panel/rankingEslabones" class="btn btn-warning" style="float:left; margin-top:17px; margin-left: 15px;" > Ver </a>
	</div>
</div>

app/views/admin_panel/rankingEslabones.html.erb
<h2 style="margin-top: 35px;"> Ranking de usuarios por cantidad de eslabones: </h2>
<table class="table" style="margin-top: 15px;">
      <tr>
            <th> Cantidad Eslabones </th>
            <th> Nombre </th>
            <th> Apellido </th>
            <th> Correo </th>
            <th> Perfil </th>
      </tr>
      <% @users.each do |user| %>
            <tr>
              <td> <%= user.eslabon %> </td>
              <td> <%= user.first_name %> </td>
              <td> <%= user.last_name %> </td>
              <td> <%= user.email %> </td>
              <td> <%= link_to "Ver Perfil" , User.find(user.id), class: "btn btn-info btn-md" %> </td>
            </tr>
      <% end %>
</table>

app/views/admin_panel/recaudacion.html.erb
<style type="text/css">
  p{ 
  font-size: 17px;
  margin-left: 15px;
  } 
</style>

<h2 style="margin-top: 40px;"> Seleccione dos fechas para buscar recaudaciones:</h2>

<div class="row" style="
  padding: 50px; 
  padding-top: 5px;
  padding-bottom: 5px;
  background-color: #D8D8D8; 
  margin-right:30px; 
  margin-left:30px;
  margin-top: 15px;
  margin-bottom:22px;
  border-radius: 17px;
  border: solid;"
>
  
<%= form_tag("/admin_panel/recaudacion") do %>
  <%= hidden_field_tag(:send, true) %>
  <div class="row" style="padding: 10px;">
    <div class="col-md-5">
      Fecha de inicio
      <%= date_select :pay, "inicio",  :order => [:day, :month, :year] %>
    </div>
    <div class="col-md-5">
      Fecha de Fin
      <%= date_select :pay, "fin", :order => [:day, :month, :year] %>
    </div>
    <div class="col-md-2">
      <%= submit_tag("Buscar", class: 'btn btn-info btn-md', style:"") %>
    </div>
  </div>
<% end %>

</div> 


<% if @pays %>
<h2 style="margin-top: 35px;"> Compras de eslabones desde <%= @inicio %> hasta <%= @fin %> : </h2>
<table class="table" style="margin-top: 15px;">
      <tr>
            <th> Cantidad Eslabones</th>
            <th> Precio por eslabon </th>
            <th> Usuario </th>
            <th> Fecha </th>
            <th> Total Gastado </th>
      </tr>
      <% total = 0 %>
      <% @pays.each do |pay|  
            gasto_user =  pay.cantidad_eslabones * pay.costo_eslabon
            total = total + gasto_user
      %>
            <tr>
              <td> <%= pay.cantidad_eslabones %> </td>
              <td> <%= pay.costo_eslabon %> </td>
              <td> <%= link_to User.find(pay.user_id).first_name , User.find(pay.user_id) %> </td>
              <td> <%= pay.created_at %> </td>
              <td> <%= gasto_user %> </td>
            </tr>
      <% end %>
      <tr>
        <td colspan="4" style="text-align: right;"><h3>Total recaudado entre estas fechas -></h3></td>
        <td> <h3><%= total %></h3> </td>
      </tr>
</table>
<% end %>