config/routes.rb
Rails.application.routes.draw do

  get 'comments/index'

  get 'pay/new'

  get 'pay/show'

  get 'notificaciones/index'
  get 'notificaciones/marcarVitoRespuesta/:id' => 'notificaciones#marcarVitoRespuesta'

  get 'admin_panel/index'
  post 'admin_panel/recaudacion' => 'admin_panel#recaudacion'
  get 'admin_panel/recaudacion' => 'admin_panel#recaudacion'
  get 'admin_panel/rankingEslabones' => 'admin_panel#rankingEslabones'

  get 'users/passForm'
  post 'users/passReset'
  get 'users/passReset'

  get 'ranking/destroy/id'

  get 'ranking/new'

  get 'ranking/edit'

  get 'ranking/index'

  get 'ranking/id'

  post 'ranking/create'

  get 'ranking/update'

  get 'ranking/destroy'

  get 'ranking/show'

  root 'home#index'

  post 'comments/new' => 'comments#new'
  post 'comments/responder' => 'comments#responder'
  post 'comments/delete' => 'comments#delete'

  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :users
  resources :favors
  get 'favors/postulantes/:id' => 'favors#postulantes'
  get 'favors/aceptar_postulante/:favor/:id' => 'favors#aceptar_postulante'
  get 'favors/marcarComoRealizado/:favor' => 'favors#marcarComoRealizado'
  get 'favors/marcarComoNoRealizado/:favor' => 'favors#marcarComoNoRealizado'
  resources :offers
  post 'offers/new'
  get 'offers/marcarVistoPostulacion/:favor' => 'offers#marcarVistoPostulacion'
  get 'offers/marcarVistoRealizacion/:favor' => 'offers#marcarVistoRealizacion'
  
  resources :ranking
  resources :admin_panel
  resources :pay
  post 'pay/new'

end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #Relaciones
  has_many :offers
  has_many :favors
  has_many :comments
  has_many :buys
  has_many :pays

  after_create :assign_default_role

  def assign_default_role
    add_role(:usuario) if self.roles.blank?
  end

  scope :by_email, -> email { where(email: email) }
  validates_presence_of :first_name, :last_name, :secret_question, :age
  validates_inclusion_of :age, in: 18..99


end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

def current_user?(user)
  @current_user == user
end 
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

  def show
  	@user=User.find(params[:id])
  	Ranking.all.each do |ranking| 
			if(ranking.cantidad_eslabones <= @user.eslabon )
				@a = ranking.titulo 
			end
  	end
    @favores = @user.favors.order('id DESC')
  end

  def edit    
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to "/"
  end

  def passReset
    if current_user 
      flash[:danger] = "Usted se encuentra actualmente logueado en su cuenta"
      redirect_to ('/')
  	elsif (params[:email].blank?  )
  		flash[:danger] = "Debe indicar su correo"
  		redirect_to :back
  	
  	elsif (params[:secret_question].blank?  )
  		flash[:danger] = "Debe indicar su una respuesta a la pregunta"
  		redirect_to :back
  	
  	elsif (User.by_email(params[:email]).count == 1)
		user = User.by_email(params[:email]).first
    @pass = Random.new.rand(11111111..99999999)
		if (user.secret_question == params[:secret_question])
			user.password = @pass
			user.password_confirmation = @pass
  			if user.save
  			else 
  				flash[:danger] = "Se produjo algun error por favor intente nuevamente"
  				redirect_to :back
  			end
  		else
  			flash[:danger] = "La respuesta a la pregunta no es valida"
  			redirect_to :back
  		end
	else
		flash[:danger] = "No existe usuario con el correo: "+params[:email]
		redirect_to :back
	end

  end

  def passForm
    if current_user 
      flash[:danger] = "Usted se encuentra actualmente logueado en su cuenta"
      redirect_to ('/')
    end
  end






end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/passForm.html.erb
<%= form_tag '/users/passReset' do %>
	
	<table class="table" style="margin-top: 25px;">
		<tr>
			<td>
			<%= label_tag :email, 'Correo: ' %>
			</td>
			<td>
				<%= text_field_tag :email  %>
			</td>
		</tr>
		<tr>
			<td>
			<%= label_tag :secret_question, "Pregunta secreta: ¿Cuál es tu color favorito?" %>
			</td>
			<td>
				<%= text_field_tag :secret_question %>
			</td>
		</tr>
		<tr>
			<td colspan="2" align="center">
			<%= submit_tag 'Recuperar Contraseña', class: "btn btn-danger" %></td>
		</tr>
	</table>
<% end %>

app/views/users/passReset.html.erb
<div class="panel panel-primary" style="margin-top: 25px;">
  <div class="panel-body">
    <h1>Contraseña alternativa</h1>
  </div>
  <div class="panel-footer">
  	<h2>Su contraseña temporal es:  <%= @pass %> <br>
  	Ingrese a su cuenta para modificarla.</h2>
  </div>
  <div class="panel-footer" style="text-align: center;">
  	<%= link_to 'Iniciar Sesión Ahora', new_user_session_path, :class => "btn btn-warning"%>
  </div>
</div>

app/views/users/show.html.erb
<script type="text/javascript">
	function muestra_oculta(contenido){
		document.getElementById("favores").style.display = "none";
		document.getElementById("postulaciones").style.display = "none";
		document.getElementById("gauchadasRealizadas").style.display = "none";
		document.getElementById(contenido).style.display = "block";

	}  
</script>

<style type="text/css">
  p{ 
	font-size: 17px;
	margin-left: 15px;
  }	

  .marcoUser{
  	padding: 50px; 
	padding-top: 5px;
	padding-bottom: 5px;
	background-color: #D8D8D8; 
	margin-right:30px; 
	margin-left:30px;
	margin-top: 20px;
	border-top-left-radius: 20px;
	border-top-right-radius: 20px;
  }

  .barraBotones{
  	background-color:#F2F2F2; 
  	margin-top:15px; 
  	margin-bottom:15px; 
  	padding-top: 7px; 
  	padding-bottom: 7px;
  }

  .barraElemento{
  	padding: 50px; 
	padding-top: 5px;
	padding-bottom: 5px;
	background-color: #D8D8D8; 
	margin-right:30px; 
	margin-left:30px;
	margin-bottom:20px;
	display:none;
  }

</style>
	

<!-- DATOS DE USUARIO -->

<div class="row marcoUser">     
	<div class="row">
		<div class="col-md-6">
			<% if current_user %>
			<% if current_user.id == @user.id %>
				<h2>Mi Perfil</h2>
			<% else %>
				<h2>Perfil de <%= @user.first_name+" "+@user.last_name%></h2>
			<% end %>
			<% end %>
		</div>
		<div class="col-md-2" style="margin-top: 20px">
		<% if current_user and can? :update, @user %>
			<!--agregar un favor-->
		<% end %>
		</div>
		<div class="col-md-2" style="margin-top: 20px">
		<% if current_user and can? :update, @user %>
			<%= link_to 'Comprar eslabones', pay_show_path, class: 'btn btn-primary' %>
		<% end %>
		</div>
		<div class="col-md-2" style="margin-top: 20px">
		<% if current_user and can? :update, @user %>
			<%= link_to 'Modificar Datos', edit_user_registration_path, class: 'btn btn-primary' %>
		<% end %>
		</div>

	</div>

	<div class="row" style="background-color:#F2F2F2">
	  	<div class="row">
	  		<div class="col-md-2" style="margin-top: 35px;">
	  			<% if @user.genre=="Masculino"%>
				<%= image_tag "user_predef_hombre.png" , size: "120x120", class:"img-responsive", style: "margin-right:auto; margin-left:auto;"%>
				<%else%>
				<%= image_tag "user_predef_mujer.png" , size: "120x120", class:"img-responsive" %>
				<%end%>
	  		</div>
	  		<div class="col-md-10">
	  		<div class="row">
	  		<div class="col-md-12" style="margin-top: 20px">
	  			<p><i>Nombre y Apellido:  </i><b><%= @user.first_name+" "+@user.last_name%></b></p>
	  		</div>
	  	</div>
	  	<div class="row">
	  		<div class="col-md-12"><p><i>Edad:</i> <%= @user.age %> </p></div>
	  	</div>
	  	<div class="row">
	  		<div class="col-md-12">
	  		<p><i>Genero:</i> <%= @user.genre %></p>
	  		</div>
	  	</div>
	  	<% if current_user %>
	  	<% if current_user.id == @user.id %>
	  	<div class="row">
			<div class="col-md-12">
	  		<p><i>Cantidad de eslabones:</i> 
              <% if @user.eslabon < 0 %>
                <span style="color: red;"><%= @user.eslabon %></span>
              <% else %>
                <%= @user.eslabon %>
              <% end %>
        </p>
	  		</div>
	  	</div>
	  	<%end%>
	  	<%end%>
		<div class="row">
	  		<div class="col-md-12">
	  		<p><i>Logro:</i> <%= link_to @a, ranking_index_path %> </p>
	  		</div>
	  	</div>
	</div>
</div>
</div>

	<div class="row barraBotones">
		<ul class="nav nav-pills nav-justified" >
  			<li role="presentation">
  				<a onclick="muestra_oculta('favores')" >
  					<% if current_user %>
  						<% if current_user.id == @user.id %> Mis <% end %> 
  					<% end %> Gauchadas
  				</a>
  			</li>

  			<% if current_user %>
  			<% if current_user.id == @user.id %>
  			<li role="presentation">
  				<a onclick="muestra_oculta('postulaciones')" >
  					Postulaciones
  				</a>
  			</li>
  			<% end %>
  			<% end %>

  			<li role="presentation">
  				<a  onclick="muestra_oculta('gauchadasRealizadas')">
  					Gauchadas Realizadas
  				</a>
  			</li>
		</ul>
	</div>
</div>


<!-- LISTADO DE MIS FAVORES -->
<div id="favores" class="row barraElemento" style="display: block;">     
	<div class="row">
		<div class="col-md-12">
			<h2>
			<% if current_user %>
				<% if current_user.id == @user.id %> Mis <% end %>
			<% end %>  Gauchadas Publicadas
			</h2>
		</div>
	</div>

	<div class="row" style="background-color:#F2F2F2">
		<div class="col-md-12">
			<table class="table">
				<tr>
            		<th> Foto </th>
            		<th> Titulo</th>
            		<th> Ubicacion</th>
            		<th> Descripción </th>
            		<th> Estado </th>
            		<th> Acciones </th>
      			</tr>
      		<% @favores.each do |favor| %>
            	<tr>
                	<td> 
                <%= link_to favor do %>
                    <% if favor.foto == '' %>
                        <%= image_tag "sin.gif", :alt => "Sin Foto",  height: 'auto', width: '70', class: "img-rounded", style:"" %>
                        <% else %>
                              <%= image_tag favor.foto , :alt => "Foto",  
                              height: 'auto', width: '70', style:"" %>
                        <% end %>
                    <% end %>
                  	</td>
                  	<td> <%= link_to favor.titulo, favor %> </td>
                  	<td> <%= link_to favor.ubicacion, favor %> </td>
                  	<td> <%= link_to favor.descripcion, favor %> </td>
                  	<td> <%= favor.estadoActual %> </td>
                  	<td> 
                  		<% if current_user and can? :update, favor and can? :destroy, favor and favor.estado == 'a'%>
            				<a href="/favors/postulantes/<%= favor.id %>" 
            				class="btn btn-primary btn-xs" style="margin-top:10px;">Lista Postulantes</a>

            				<%= link_to "Editar", edit_favor_path(favor), 
            				class: 'btn btn-danger btn-xs', style:"margin-top:10px;"%>
            
           					<%= link_to "Eliminar",favor, method: :delete, 
           					class: 'btn btn-danger btn-xs', style:"margin-top:10px;" , :onclick => "return confirmar('Eliminar el favor');"%>
                  		 <% elsif favor.estado == 'p' %>
                  		 	<a href="/favors/marcarComoRealizado/<%= favor.id %>" 
            				class="btn btn-success btn-xs" style="margin-top:10px;" onclick ="return confirmar('Marcar como realizado');")>
            				Realizado</a>

            				<a href="/favors/marcarComoNoRealizado/<%= favor.id %>" 
            				class="btn btn-danger btn-xs" style="margin-top:10px;" onclick ="return confirmar('Marcar como NO realizado');">
            				No Realizado</a>
                  		 <% end %>
                  	</td>
           		</tr>
      		<% end %>
			</table>
		</div>
	</div>
</div>


<!-- LISTADO DE MIS POSTULACIONES -->
<div id="postulaciones" class="row barraElemento">     
	<div class="row">
		<div class="col-md-12"><h2>Mis Postulaciones</h2></div>
	</div>
	<% if current_user %>
	<div class="row" style="background-color:#F2F2F2">
		<div class="col-md-12">
			<table class="table">
				<tr>
            		<th> Foto </th>
            		<th> Titulo</th>
            		<th> Usuario </th>
            		<th> Correo de Contacto</th>
            		<th> Estado </th>
      			</tr>
      		<% current_user.offers.order('id DESC').each do |offer| 
      			favor = Favor.find(offer.favor_id)
      			if !(favor.estado == 'r' or favor.estado == 'nr')
      		%>
      			<tr>
      				<td>
      				<%= link_to favor do %>
                    <% if favor.foto == '' %>
                        <%= image_tag "sin.gif", :alt => "Sin Foto",  height: 'auto', width: '70', class: "img-rounded", style:"" %>
                        <% else %>
                              <%= image_tag favor.foto , :alt => "Foto",  
                              height: 'auto', width: '70', style:"" %>
                        <% end %>
                    <% end %>
                  	</td>
                  	<td> <%= link_to favor.titulo, favor %> </td>
                  	<td> 
                  		<% nombre = favor.user.last_name+" "+favor.user.first_name %>
                  		<%= link_to nombre, favor.user %>
                  	</td>
                  	<% if offer.otorgado == true %>
                  		<td><%= favor.user.email %></td>
                  		<td> 
                  			<% if favor.estado == 'p' %>
                  				Postulacion Aceptada 
                  			<% elsif favor.estado == 'r' %>
                  				¡ Realizaste la Gauchada !
                  			<% end %>
                  		</td>
                  	<% else %>
                  		<td> Info aun no disponible </td>
                  		<td> No Otorgado </td>
                  	<% end %>
            	</tr>
            	<% end %>
      		<% end %>
			</table>
		</div>
	</div>
	<% end %>
</div>



<div id="gauchadasRealizadas" class="row barraElemento">     
	<div class="row">
		<div class="col-md-12"><h2>Gauchadas Realizadas</h2></div>
	</div>
	<% if current_user %>
	<div class="row" style="background-color:#F2F2F2">
		<div class="col-md-12">
			<table class="table">
				<tr>
            		<th> Foto </th>
            		<th> Titulo</th>
            		<th> Usuario </th>
            		<th> Correo de Contacto</th>
            		<th> Estado </th>
      			</tr>
      		<% current_user.offers.order('id DESC').each do |offer| 
      			favor = Favor.find(offer.favor_id)
      			if (favor.estado == 'r' or favor.estado == 'nr')
      		%>
      			<tr>
      				<td>
      				<%= link_to favor do %>
                    <% if favor.foto == '' %>
                        <%= image_tag "sin.gif", :alt => "Sin Foto",  height: 'auto', width: '70', class: "img-rounded", style:"" %>
                        <% else %>
                              <%= image_tag favor.foto , :alt => "Foto",  
                              height: 'auto', width: '70', style:"" %>
                        <% end %>
                    <% end %>
                  	</td>
                  	<td> <%= link_to favor.titulo, favor %> </td>
                  	<td> 
                  		<% nombre = favor.user.last_name+" "+favor.user.first_name %>
                  		<%= link_to nombre, favor.user %>
                  	</td>
                  	<% if offer.otorgado == true %>
                  		<td><%= favor.user.email %></td>
                  		<td> 
                  			<% if favor.estado == 'p' %>
                  				Postulacion Aceptada 
                  			<% elsif favor.estado == 'r' %>
                  				¡ Realizaste la Gauchada !
                  			<% elsif favor.estado == 'nr' %>
                  				NO realizaste la Gauchada :(
                  			<% end %>
                  		</td>
                  	<% else %>
                  		<td> Info aun no disponible </td>
                  		<td> No Otorgado </td>
                  	<% end %>
            	</tr>
            	<% end %>
      		<% end %>
			</table>
		</div>
	</div>
	<% end %>
</div>

<!--
Activo (a) -> Eliminado (e)
Activo (a) -> Pendiente (p) -> Realizado / No realizado


-->