config/routes.rb
Rails.application.routes.draw do

  get 'comments/index'

  get 'pay/new'

  get 'pay/show'

  get 'notificaciones/index'
  get 'notificaciones/marcarVitoRespuesta/:id' => 'notificaciones#marcarVitoRespuesta'

  get 'admin_panel/index'
  post 'admin_panel/recaudacion' => 'admin_panel#recaudacion'
  get 'admin_panel/recaudacion' => 'admin_panel#recaudacion'
  get 'admin_panel/rankingEslabones' => 'admin_panel#rankingEslabones'

  get 'users/passForm'
  post 'users/passReset'
  get 'users/passReset'

  get 'ranking/destroy/id'

  get 'ranking/new'

  get 'ranking/edit'

  get 'ranking/index'

  get 'ranking/id'

  post 'ranking/create'

  get 'ranking/update'

  get 'ranking/destroy'

  get 'ranking/show'

  root 'home#index'

  post 'comments/new' => 'comments#new'
  post 'comments/responder' => 'comments#responder'
  post 'comments/delete' => 'comments#delete'

  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :users
  resources :favors
  get 'favors/postulantes/:id' => 'favors#postulantes'
  get 'favors/aceptar_postulante/:favor/:id' => 'favors#aceptar_postulante'
  get 'favors/marcarComoRealizado/:favor' => 'favors#marcarComoRealizado'
  get 'favors/marcarComoNoRealizado/:favor' => 'favors#marcarComoNoRealizado'
  resources :offers
  post 'offers/new'
  get 'offers/marcarVistoPostulacion/:favor' => 'offers#marcarVistoPostulacion'
  get 'offers/marcarVistoRealizacion/:favor' => 'offers#marcarVistoRealizacion'
  
  resources :ranking
  resources :admin_panel
  resources :pay
  post 'pay/new'

end

app/models/ranking.rb
class Ranking < ActiveRecord::Base
	validates_uniqueness_of :titulo
	validates_uniqueness_of :cantidad_eslabones
	default_scope ->{order("cantidad_eslabones")}
end

app/controllers/ranking_controller.rb
class RankingController < ApplicationController
  
  def index
   @rankings = Ranking.all;
  end

  def show
   @ranking= Ranking.find(params[:id])
  end

  def new
  	@ranking = Ranking.new
  end

 def create
 	if can? :create, Ranking
  		@ranking = Ranking.new
  		@ranking.titulo=params[:ranking][:titulo]
  		@ranking.cantidad_eslabones=params[:ranking][:cantidad_eslabones]
  		
 		 if @ranking.save
        	flash[:success] = "El logro ha sido creado exitosamente."
        	redirect_to ("/ranking/index")
    	 else 
        	flash[:danger] = "Ya existe un logro con ese nombre o eslabones necesarios."
        	redirect_to (:back)
 		   end
 	else
 	 	  flash[:danger] = "No tienes los permisos necesarios para crear un Logro."
      redirect_to (:back)
  end

  def edit

  if can? :update, Ranking 
      @ranking = Ranking.find(params[:id])  
  else 
      flash[:danger] = "No cuenta con los permisos para editar."
      redirect_to ("/")
  end  
  end

 	end

def destroy
  if can? :destroy, Ranking 
    ranking = Ranking.find(params[:id])
   if ranking.cantidad_eslabones != Ranking.first.cantidad_eslabones
    if ranking.destroy
      flash[:success] = "El Logro ha sido eliminado exitosamente."
      redirect_to ("/ranking/index")
    else
      flash[:danger] = "No se pudo eliminar el logro"
      redirect_to ('/ranking/index')
    end
  else
    flash[:danger] = "Este logro no puede ser eliminado"
    redirect_to ("/ranking/index")
  end
  else 
      flash[:danger] = "No cuenta con los permisos para eliminar."
      redirect_to ("/")
  end
end
def update
  if can? :update, Ranking
    @ranking = Ranking.find(params[:id])
    if @ranking.cantidad_eslabones != Ranking.first.cantidad_eslabones
      @ranking.titulo = params[:ranking][:titulo]
      @ranking.cantidad_eslabones = params[:ranking][:cantidad_eslabones]
      if @ranking.save
        flash[:success] = "El Logro ha sido actualizado exitosamente."
        redirect_to @ranking
      else 
        flash[:danger] = "Ya existe un logro con ese nombre o eslabones necesarios."
        redirect_to (:back)
      end
      else
      flash[:danger] = "Este Logro no se puede editar"
      redirect_to ("/ranking/index")
      end
    end
  end
end

app/helpers/ranking_helper.rb
module RankingHelper
end

app/helpers/rankings_helper.rb
module RankingsHelper
end

app/views/ranking/edit.html.erb
<style type="text/css">
  .mensaje{
    margin: 25px;
    width: 650px;
    height: auto;
    font-size: 18px;
    padding: 6px;
    border-radius: 12px;
  }
</style>

<h1> Editar Logro</h1>


<%= form_for Ranking.find(params[:id]) , url: {action:"update"} do |r| %>
  <table class="table">
    <tr>
      <td><%= r.label :titulo %></td>
      <td>
      <%= r.text_field :titulo, class: 'form-control', label: 'titulo', placeholder: 'Ingrese el titulo' , :required => true,  size: 50%>
      </td>
    </tr>

    <tr>
      <td><%= r.label :cantidad_eslabones %></td>
      <td>
       <input value="" type="tel" label="cantidad_eslabones" required="required" 
        name="ranking[cantidad_eslabones]" id="ranking_cantidad_eslabones"  pattern="-?[0-9]{0,4}">
      
        </td>
    </tr>

    <tr>
      <td colspan="2" align="center" >
        <%= r.submit "Modificar Logro", class: 'btn btn-primary' %>
      </td>
    </tr>
  </table>
<% end %>

app/views/ranking/index.html.erb
<div class="row">
  <div class="col-sm-2">
    <h1>Logros</h1>
  </div>
    <% if can? :create, Ranking %>
       <div class="col-sm-2" style='margin-top:20px'>
       <%= link_to "Nuevo Logro", new_ranking_path(@ranking), class: 'btn btn-success btn-md'%>  
      </div>
    <%end %>
  </div>

  <div class="row">
    <div class="col-sm-2">
     <h4 style="text-align:center;"">  Titulo </h4>
    </div>
    <div class="col-sm-3">
      <h4> Eslabones necesarios</h4>
    </div>
  </div>
<% @rankings.each do |ranking| %>
 <div class="row">
    <div class="col-sm-2">

      <%  if can? :update, Ranking %>
        <pre style="text-align:center; "><a href=/ranking/<%=ranking.id%>> <%=ranking.titulo%> </a></pre>
      <% else %>
        <pre style="text-align:center;""><%= ranking.titulo%></pre>
      <% end %>
    </div>
    <div class="col-sm-2">
      <pre style="text-align:center;""><%= ranking.cantidad_eslabones%></pre>	
    </div>
  </div>
<%end %>
</div>

app/views/ranking/new.html.erb
<style type="text/css">
  .mensaje{
    margin: 25px;
    width: 650px;
    height: auto;
    font-size: 18px;
    padding: 6px;
    border-radius: 12px;
  }
</style> 

<h1> Crear un Logro </h1>

<%= form_for @ranking , url: {action:"create"} do |r| %>
  <table class="table">
    <tr>
      <td><%= r.label :titulo %></td>
      <td>
      <%= r.text_field :titulo, label: 'titulo', placeholder: 'Ingrese el titulo' , :required => true , size: 50 %>
      </td>
    </tr>

    <tr>
      <td><%= r.label :cantidad_eslabones %></td>
      <td>
       <input value="" type="tel" label="cantidad_eslabones" required="required" 
        name="ranking[cantidad_eslabones]" id="ranking_cantidad_eslabones"  pattern="-?[0-9]{0,4}">
      
        </td>
    </tr> 

    <tr>
      <td colspan="2" align="center" >
        <%= r.submit "Dar de alta", class: 'btn btn-primary' %>
      </td>
    </tr>
  </table>
<% end %>

app/views/ranking/show.html.erb
<h1>Logro</h1>


  <div class="row">
    <div class="col-sm-2">
     <h4 style="text-align:center;"">  Titulo </h4>
    </div>
    <div class="col-sm-3">
      <h4> Eslabones necesarios</h4>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-3">

     <pre style="text-align:center; "><%= @ranking.titulo %></pre> 
    </div>
    <div class="col-sm-3">
      <pre style="text-align:center;""><%= @ranking.cantidad_eslabones%></pre>	
    </div>
    <div class="col-sm-3">
       <%= link_to "Editar", edit_ranking_path(@ranking), class: 'btn btn-success btn-md'%>	
    </div>
    <div class="col-sm-3">
      	
    <%= link_to "Eliminar", @ranking , method: :delete, class: 'btn btn-success btn-md'%> 
    </div>
  </div>
  