config/routes.rb
Rails.application.routes.draw do

  get 'comments/index'

  get 'pay/new'

  get 'pay/show'

  get 'notificaciones/index'
  get 'notificaciones/marcarVitoRespuesta/:id' => 'notificaciones#marcarVitoRespuesta'

  get 'admin_panel/index'
  post 'admin_panel/recaudacion' => 'admin_panel#recaudacion'
  get 'admin_panel/recaudacion' => 'admin_panel#recaudacion'
  get 'admin_panel/rankingEslabones' => 'admin_panel#rankingEslabones'

  get 'users/passForm'
  post 'users/passReset'
  get 'users/passReset'

  get 'ranking/destroy/id'

  get 'ranking/new'

  get 'ranking/edit'

  get 'ranking/index'

  get 'ranking/id'

  post 'ranking/create'

  get 'ranking/update'

  get 'ranking/destroy'

  get 'ranking/show'

  root 'home#index'

  post 'comments/new' => 'comments#new'
  post 'comments/responder' => 'comments#responder'
  post 'comments/delete' => 'comments#delete'

  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :users
  resources :favors
  get 'favors/postulantes/:id' => 'favors#postulantes'
  get 'favors/aceptar_postulante/:favor/:id' => 'favors#aceptar_postulante'
  get 'favors/marcarComoRealizado/:favor' => 'favors#marcarComoRealizado'
  get 'favors/marcarComoNoRealizado/:favor' => 'favors#marcarComoNoRealizado'
  resources :offers
  post 'offers/new'
  get 'offers/marcarVistoPostulacion/:favor' => 'offers#marcarVistoPostulacion'
  get 'offers/marcarVistoRealizacion/:favor' => 'offers#marcarVistoRealizacion'
  
  resources :ranking
  resources :admin_panel
  resources :pay
  post 'pay/new'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    #Todos los permisos CRUD
    alias_action :create, :read, :update, :destroy, :to => :crud
    alias_action :create, :read, :destroy, :to => :crd 
    alias_action :create, :read, :to => :cr
    alias_action :update, :destroy, :to => :ud

    #Cuando el Usuario No esta registrado
    user ||= User.new  

    if (user.has_role? :usuario)  
        can :crud , User , :id => user.id
        
        can :ud, Favor , :user_id => user.id
        can :cr, Favor
        
        can :read , Ranking
        cannot :create, Ranking
        cannot :update, Ranking
        cannot :destroy, Ranking
    end
    if user.has_role? :admin
        can :crud, User
        #can :crud, CouchType
        can :crud, Favor
        #can :crud, Reservation
        can :crud, Ranking
    else 
        #can :read, Couch
    end




    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :favor
	belongs_to :user
end

app/models/favor.rb
class Favor < ActiveRecord::Base
	has_many :offers
	has_many :comments
	belongs_to :user
	
	validates_uniqueness_of :titulo

	def postulado(id)
		if self.offers.where("user_id = "+id.to_s).count > 0 
			return true
		end
		return false
	end

	def postulante
		if self.estado == 'p'
			return self.offers.where("otorgado = true").last.user.id
		else
			return -1
		end
	end

	def estadoActual
		if self.estado == 'a' 
            estado = "Activo" 
        elsif self.estado == 'e'
            estado = "Eliminado"
        elsif self.estado == 'p'
            estado = "Pendiente"
        elsif self.estado == 'r'
            estado = "Finalizado, Exitoso"
        elsif self.estado == 'nr'
            estado = "Finalizado, No cumplido"
        end
        return estado
	end

	def isPropietario(user)
		return self.user_id == user.id
	end
end

app/models/offer.rb
class Offer < ActiveRecord::Base
	belongs_to :user
	belongs_to :favor

	def is_pendiente?
		rta = false
		if(self.visto == "false")
			rta = true
		end
		return rta
	end

end

app/models/pay.rb
class Pay < ActiveRecord::Base
	belongs_to :user
end

app/models/ranking.rb
class Ranking < ActiveRecord::Base
	validates_uniqueness_of :titulo
	validates_uniqueness_of :cantidad_eslabones
	default_scope ->{order("cantidad_eslabones")}
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #Relaciones
  has_many :offers
  has_many :favors
  has_many :comments
  has_many :buys
  has_many :pays

  after_create :assign_default_role

  def assign_default_role
    add_role(:usuario) if self.roles.blank?
  end

  scope :by_email, -> email { where(email: email) }
  validates_presence_of :first_name, :last_name, :secret_question, :age
  validates_inclusion_of :age, in: 18..99


end

app/controllers/pay_controller.rb
class PayController < ApplicationController
  def show
  end

  def new 
  		
		pay = Pay.new
		pay.cantidad_eslabones = params[:cantidad_eslabones]
		pay.costo_eslabon = '12'
		pay.user_id = current_user.id
		if pay.save
  			flash[:success] = "La compra fue realizada correctamente"
  			current_user.eslabon = current_user.eslabon + pay.cantidad_eslabones
  			current_user.save
      	else
      		flash[:danger] = "Algo salio mal, no se ha podido realizar la compra"
      	end
      	redirect_to ('/')
	end

end

app/helpers/admin_panel_helper.rb
module AdminPanelHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favors_helper.rb
module FavorsHelper
end

app/helpers/gauchada_helper.rb
module GauchadaHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/pay_helper.rb
module PayHelper
end

app/helpers/ranking_helper.rb
module RankingHelper
end

app/helpers/rankings_helper.rb
module RankingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<style type="text/css">
	.footer{
		position: absolute;
		left: 0;
		bottom: 0;
		padding: 4px;
		height: 50px;
		width: 100%;
		background-color: #E0E0E0;
		color: #000;
	}
</style>

<footer class="footer">
	<div class="container">
		<%= image_tag "logo.png" , style:"height: 40px;float: left;", class:"img-responsive" %>
		<p style="float: left; margin-top: 10px;">
			Proyecto Gauchada, cadena de favores. Todos los derechos reservados PGT Software.
		</p>
	</div>
</footer>

app/views/layouts/_header.html.erb
<header>

<style type="text/css">
	.nav > li > a:focus, .nav > li > a:hover {
    	background-color: #F27321;
    	color: #FFF;
    	border-radius: 0px;
    	margin-right: 3px;
    	margin-left: 3px;
	}

	.nav > li > a{
		margin-right: 3px;
    		margin-left: 3px;
	}

	.nav-pills > li.active > a, .nav-pills > li.active > a:focus, .nav-pills > li.active > a:hover {
    		color: #fff;
        background-color: #F27321;
        border-radius: 0px;
        margin-right: 3px;
    		margin-left: 3px;
	}
</style>

<div class="container">
		<%= link_to "/" do %>
			<%= image_tag "eslogan.png" , class:"img-responsive" %>
			
		<% end %>
</div>

<div class="row" style="background-color: #000; padding-top: 6px; padding-bottom: 6px; margin-right: 0px;">
	<div class="col-sm-12 col-md-12">
    <div class="container">
		<ul class="nav nav-pills nav-justified" >

  			<li role="presentation" 
  				<%- if controller_name == 'home' %> class="active" <% end %> >
  				<a href="/">Home</a>
  			</li>

  			<% if current_user %> 

  				<li role="presentation"
  					<%- if controller_name == 'favors' %> class="active" <% end %> >
  					<%= link_to "Publicar Gauchada", new_favor_path() , action: "new" %>
  				</li>	

          <li role="presentation"
            <%- if controller_name == 'notificaciones' %> class="active" <% end %> >
            <a href="/notificaciones/index">Notificaciones <span class="badge">
            <%= cantidadNotificaciones %></span></a>
          </li>

  				<li role="presentation"
            <%- if controller_name == 'users' %> class="active" <% end %> >
            <%= link_to "Perfil de "+current_user.first_name , current_user %>
          </li>

          <% if current_user.has_role? :admin %>
            <li role="presentation" 
              <%- if controller_name == 'admin_panel' %> class="active" <% end %> >
              <%= link_to 'Configuraciones', "/admin_panel" %>
            </li>
          <% end %>

          <li role="presentation">
            <%= link_to 'Cerrar Sesion', destroy_user_session_path, method: :delete %> 
          </li>
			<% else %>
				
				<li role="presentation" 
					<%- if controller_name == 'sessions' %> class="active" <% end %> >
    				<%= link_to 'Iniciar Sesión', new_user_session_path %>
    			</li>

				<li role="presentation" 
					<%- if controller_name == 'registrations' %> class="active" <% end %> >
    			<%= link_to 'Registrarse', new_user_registration_path %>
    		</li>
			<% end %>
		</ul>
    </div>
	</div>
</div>



</header>

app/views/layouts/application.html.erb
<style type="text/css">
  html{position: relative; min-height: 100%;}

  .msj{
    margin-top: 15px; 
    margin-bottom: 15px;
    padding: 2px;
    color: #FFF;
    text-align: center;
  }
</style>

<!DOCTYPE html>
<html>
<head>
  <title>Gauchada</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body style="margin-bottom: 65px;">

<%= render 'layouts/header' %>

<% if notice %>
<div class="alert alert-success alert-dismissible msj" role="alert" >
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <h3><%= notice %></h3>
</div>
<% end %>

<% if alert %>
<div class="alert alert-warning alert-dismissible msj" role="alert" >
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <h3><%= alert %></h3>
</div>
<% end %>


<% if flash[:success]%>
  <div class="alert alert-success alert-dismissible msj" role="alert" >
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <h3><%=flash[:success]%></h3>
  </div>
<%end%>

<% if flash[:danger]%>
  <div class="aalert alert-warning alert-dismissible msj" role="alert" >
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <h3><%=flash[:danger]%></h3>
  </div>
<%end%>
 

<div class="container">
	<%= yield %>
</div>


<%= render 'layouts/footer' %>


</body>
</html>